apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cc
  name: hello2
spec:
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
        - image: hello2
          name: hello2
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: hello2
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
