apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../prod/

nameSuffix: -green

secretGenerator:
- behavior: merge
  envs:
  - secrets.env
  name: hello1

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: hello1
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /green

patchesStrategicMerge:
  - patch/deployment.yaml

images:
- name: hello1
  newName: alex202/hello1
  newTag: 47397056a389a852f0385ba98b3ad878cf1f8a1c
