apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../prod/
- externalsecret.yaml

nameSuffix: -green

transformers:
- suffuxTransformation.yaml
- namespaceTransformer.yaml

#generators:
#  - ssmsecret.yaml

commonLabels:
  deploy: green

secretGenerator:
- behavior: merge
  name: hello1
    #envs:
    #  - secrets.env

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/path
      value: /green
  target:
    group: networking.k8s.io
    kind: Ingress
    name: hello1
    version: v1

patchesStrategicMerge:
- patch/deployment.yaml

images:
- name: hello1
  newName: alex202/hello1
  newTag: 870611cba158500d25a8971e192f99ef475c4998
