apiVersion: v1
kind: SSMSecret
metadata:
  name: whatever
  annotations:
    config.kubernetes.io/function: |-
      exec:
        path: ../../../ssmsecret.sh
region: us-east-1
data:
  SWAGGER_ENABLED: /prod/shared/swagger
  #- name: SWAGGER_ENABLED
  #  key: /prod/shared/swagger

