apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress.yaml
namespace: hello3
commonLabels:
  env: prod
secretGenerator:
  - name: hello3
    envs:
      - secrets.env



