apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cc
  name: hello1
spec:
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
        - image: hello1
          name: hello1
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: hello1
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
