apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: hello-gitops-stage
commonLabels:
  env: prod
secretGenerator:
  - name: hello-gitops-secret
    envs:
      - secrets.env
replicas:
  - name: hello-gitops
    count: 3