apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello3
spec:
  template:
    spec:
      containers:
        - name: hello3
          resources:
            limits:
              cpu: 300m
              memory: 700Mi
            requests:
              cpu: 300m
              memory: 700Mi