apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-green
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://54.197.153.149:6443
  project: hello-prod
  source:
    path: cluster/manifests/overlay/green/
    repoURL: https://gitlab.com/alex-egorov/hello-cluster.git
    targetRevision: HEAD