apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress.yaml

namespace: hello1

commonLabels:
  env: prod

secretGenerator:
  - name: hello1
    envs:
      - secrets.env






