apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world1
spec:
  template:
    spec:
      containers:
        - name: hello-world1
          resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 300m
              memory: 1000Mi