apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../prod/

nameSuffix: -blue

secretGenerator:
- behavior: merge
  envs:
  - secrets.env
  name: hello2

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/path
      value: /blue
  target:
    group: networking.k8s.io
    kind: Ingress
    name: hello2
    version: v1

replicas:
- count: 3
  name: hello2

images:
- name: hello2
  newName: alex202/hello2
  newTag: b151dc4a78360630b1efddfc1f7f0e431770d37e
