apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: hello1-aws-ssm
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
spec:
  backendType: systemManager
  # optional: specify role to assume when retrieving the data
  #roleArn: arn:aws:iam::123456789012:role/test-role
  region: us-east-1
  data:
    - key: /prod/shared/swagger
      name: SWAGGER_ENABLED
