apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../prod/

nameSuffix: -blue

transformers:
  - suffuxTransformation.yaml
  - namespaceTransformer.yaml

secretGenerator:
  - name: hello1
    behavior: merge
    #envs:
    #  - secrets.env

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/path
      value: /blue
  target:
    group: networking.k8s.io
    kind: Ingress
    name: hello1
    version: v1

replicas:
- count: 3
  name: hello1

images:
- name: hello1
  newName: alex202/hello1
  newTag: b46be43067e8dbfa2a3b136ef39df61971922935
