apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod/
nameSuffix: '-green'
secretGenerator:
  - name: hello-world1
    behavior: merge
    envs:
      - secrets.env
patches:
  - target:
      kind: Deployment
      name: hello-world1
    patch: |-
      - op: replace
        path: /spec/resources
        value:
          limits:
            cpu: 300m
            memory: 700Mi
          requests:
            cpu: 300m
            memory: 700Mi
