apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://54.147.65.213:6443
  project: hello-prod
  source:
    path: cluster/manifests/overlays/blue/
    repoURL: https://github.com/alex-egorov/hello-cluster.git
    targetRevision: HEAD
    #plugin:
    #  env:
    #    - name: SWAGGER_ENABLED
    #      value: "false"
  #syncPolicy:
  #  syncOptions:
  #    - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  orphanedResources:
    warn: false