apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 21-hello1-green
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://54.147.65.213:6443
  project: hello-prod
  source:
    path: cluster/manifests/hello1/green/
    repoURL: https://github.com/alex-egorov/hello-cluster.git
    targetRevision: HEAD
    #plugin:
    #  env:
    #    - name: SWAGGER_ENABLED
    #      value: "true"